import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationPanel } from '@/components/NavigationPanel';
import { ClientSession } from '@/components/ClientSession';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    console.log('rendering root layout...')
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ClientSession>
            <NavigationPanel/>
            <div className="min-h-screen flex items-center justify-center bg-gray-100 px-4">
                <div className=" mt-8 mb-8 max-w-screen w-full bg-white p-6 rounded-lg shadow-md">
                    {children}
                </div>
            </div>
        </ClientSession>
        </body>
        </html>
    );
}
